baseURL = "https://kelvin17.github.io/"
languageCode = "en-us"
title = "BlackBear Tech Blog"
theme = "PaperMod"

[pagination]
pagerSize = 10

[params]
env = "production"
title = "My Tech Blog"
description = "Software Fundation / Architecture & System Design/ AI/ Essay"
defaultTheme = "auto"
math = true

ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = true

[params.homeInfoParams]
Title = "Welcome to BlackBear Blog"
Content = "技术基础(Java/算法/AI) / 系统设计(金融系统架构/大数据系统架构) / 随笔(技术史话,阅读笔记)"

[menu]

[[menu.main]]
name = "Software Fundation"
url = "/tech/"
weight = 1

[[menu.main]]
name = "Architecture & System Design"
url = "/system-design/"
weight = 2

[[menu.main]]
name = "Essay"
url = "/essay/"
weight = 3